# application.yml_v1
# # Spring Boot configuration (H2 for testing)
# spring:
#   datasource:
#     url: jdbc:h2:mem:testdb
#     driver-class-name: org.h2.Driver
#     username: sa
#     password: 
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
# server:
#   port: 8080
# application.yml_v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expensetracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
app:
  jwtSecret: J546AppDaEOv5cj2J+59o8mVnYnlEHEgBFrjSxA9ab46/1Z30i/FylzakQSFVy9/VhhfRYM7XMy4lauRElzMmQ==